# Copyright (c) 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Authors:
# - Philippe Sauter <phsauter@iis.ee.ethz.ch>
services:
  pulp-docker:
    build:
      context: .
      dockerfile: Dockerfile.user
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
    image: hpretl/iic-osic-tools:2025.03-custom
    environment:
      - UID=${USER_ID}
      - GID=${GROUP_ID}
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./:/fosic/designs/croc
    stdin_open: true
    tty: true
    working_dir: /fosic/designs/croc
    entrypoint: /dockerstartup/scripts/ui_startup.sh
    command: --skip bash
